_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 15
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('rfs_trainval_base2',)
  TEST: ('rfs_test_base2',)
SOLVER:
  IMS_PER_BATCH: 12
  STEPS: (16000, 21000)
  MAX_ITER: 24000  # 17.4 epochs
  WARMUP_ITERS: 100
OUTPUT_DIR: "/media/datasets/gpu17_models/FSCE/checkpoints/rfs/faster_rcnn/faster_rcnn_R_101_FPN_base2"