_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 15
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_base3', 'voc_2012_trainval_base3')
  TEST: ('voc_2007_test_base3',)
SOLVER:
  IMS_PER_BATCH: 12
  STEPS: (24000, 32000)
  MAX_ITER: 36000  # 17.4 epochs
  WARMUP_ITERS: 100
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 5000
OUTPUT_DIR: "/media/datasets/gpu17_models/Ours/checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base3"
