_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "/media/datasets/gpu17_models/Ours/checkpoints/voc_outline/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NAME: "NovelROIHeads"
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256
    IOU_THRESHOLDS: [0.4]
    NOVEL_MODULE:
      COPY_OPTION: True
      IOU_THRESH: 0.7
      PROTOTYPES_FUSE_ALPHA: 0.2
      PROTOTYPES_FEATURE_FUSE_ALPHA: 0.2
      PROLOSS_FACTOR: 0.3
    FUSE_ALPHA: 0.08

INPUT:
  CROP:
    ENABLED: TRUE
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800

DATASETS:
  SHOTS: 3
  TRAIN: ('voc_2007_trainval_all1_3shot_seed0',)
  TEST: ('voc_2007_test_all1',)

SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.001
  GAMMA: 0.5
  STEPS: (10000,14000)
  MAX_ITER: 16000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 200

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 1000

OUTPUT_DIR: "/media/datasets/gpu17_models/Ours/checkpoints/voc_outline/faster_rcnn/split1_3shot_GPB_PFB_proloss_new"